[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://your-backend-url.onrender.com"
  VITE_WEBSOCKET_URL = "wss://your-backend-url.onrender.com"